package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Approvisionnement generated by hbm2java
 */
public class Approvisionnement implements java.io.Serializable {

	private int id;
	private Ligneapprovisionnement ligneapprovisionnement;
	private Collaborateur collaborateur;
	private Employe employe;
	private String reference;
	private Date dateapprovionnement;
	private String statut;
	private Byte montanttotal;
	private Set pieces = new HashSet(0);

	public Approvisionnement() {
	}

	public Approvisionnement(int id) {
		this.id = id;
	}

	public Approvisionnement(int id, Ligneapprovisionnement ligneapprovisionnement, Collaborateur collaborateur,
			Employe employe, String reference, Date dateapprovionnement, String statut, Byte montanttotal, Set pieces) {
		this.id = id;
		this.ligneapprovisionnement = ligneapprovisionnement;
		this.collaborateur = collaborateur;
		this.employe = employe;
		this.reference = reference;
		this.dateapprovionnement = dateapprovionnement;
		this.statut = statut;
		this.montanttotal = montanttotal;
		this.pieces = pieces;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Ligneapprovisionnement getLigneapprovisionnement() {
		return this.ligneapprovisionnement;
	}

	public void setLigneapprovisionnement(Ligneapprovisionnement ligneapprovisionnement) {
		this.ligneapprovisionnement = ligneapprovisionnement;
	}

	public Collaborateur getCollaborateur() {
		return this.collaborateur;
	}

	public void setCollaborateur(Collaborateur collaborateur) {
		this.collaborateur = collaborateur;
	}

	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Date getDateapprovionnement() {
		return this.dateapprovionnement;
	}

	public void setDateapprovionnement(Date dateapprovionnement) {
		this.dateapprovionnement = dateapprovionnement;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public Byte getMontanttotal() {
		return this.montanttotal;
	}

	public void setMontanttotal(Byte montanttotal) {
		this.montanttotal = montanttotal;
	}

	public Set getPieces() {
		return this.pieces;
	}

	public void setPieces(Set pieces) {
		this.pieces = pieces;
	}

}
