package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	private int idarticle;
	private Lignevente lignevente;

	public Article() {
	}

	public Article(int idarticle) {
		this.idarticle = idarticle;
	}

	public Article(int idarticle, Lignevente lignevente) {
		this.idarticle = idarticle;
		this.lignevente = lignevente;
	}

	public int getIdarticle() {
		return this.idarticle;
	}

	public void setIdarticle(int idarticle) {
		this.idarticle = idarticle;
	}

	public Lignevente getLignevente() {
		return this.lignevente;
	}

	public void setLignevente(Lignevente lignevente) {
		this.lignevente = lignevente;
	}

}
