package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Augmentationsalaire generated by hbm2java
 */
public class Augmentationsalaire implements java.io.Serializable {

	private int idaugmentation;
	private Contrat contrat;
	private Varietesalaire varietesalaire;
	private Date date;
	private Boolean isvalide;
	private Byte montantprecedent;
	private Byte nouveaumontant;

	public Augmentationsalaire() {
	}

	public Augmentationsalaire(int idaugmentation) {
		this.idaugmentation = idaugmentation;
	}

	public Augmentationsalaire(int idaugmentation, Contrat contrat, Varietesalaire varietesalaire, Date date,
			Boolean isvalide, Byte montantprecedent, Byte nouveaumontant) {
		this.idaugmentation = idaugmentation;
		this.contrat = contrat;
		this.varietesalaire = varietesalaire;
		this.date = date;
		this.isvalide = isvalide;
		this.montantprecedent = montantprecedent;
		this.nouveaumontant = nouveaumontant;
	}

	public int getIdaugmentation() {
		return this.idaugmentation;
	}

	public void setIdaugmentation(int idaugmentation) {
		this.idaugmentation = idaugmentation;
	}

	public Contrat getContrat() {
		return this.contrat;
	}

	public void setContrat(Contrat contrat) {
		this.contrat = contrat;
	}

	public Varietesalaire getVarietesalaire() {
		return this.varietesalaire;
	}

	public void setVarietesalaire(Varietesalaire varietesalaire) {
		this.varietesalaire = varietesalaire;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Boolean getIsvalide() {
		return this.isvalide;
	}

	public void setIsvalide(Boolean isvalide) {
		this.isvalide = isvalide;
	}

	public Byte getMontantprecedent() {
		return this.montantprecedent;
	}

	public void setMontantprecedent(Byte montantprecedent) {
		this.montantprecedent = montantprecedent;
	}

	public Byte getNouveaumontant() {
		return this.nouveaumontant;
	}

	public void setNouveaumontant(Byte nouveaumontant) {
		this.nouveaumontant = nouveaumontant;
	}

}
