package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Avis generated by hbm2java
 */
public class Avis implements java.io.Serializable {

	private int idavis;
	private Client client;
	private Integer note;
	private String commentaire;
	private Date datecreation;

	public Avis() {
	}

	public Avis(int idavis) {
		this.idavis = idavis;
	}

	public Avis(int idavis, Client client, Integer note, String commentaire, Date datecreation) {
		this.idavis = idavis;
		this.client = client;
		this.note = note;
		this.commentaire = commentaire;
		this.datecreation = datecreation;
	}

	public int getIdavis() {
		return this.idavis;
	}

	public void setIdavis(int idavis) {
		this.idavis = idavis;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Integer getNote() {
		return this.note;
	}

	public void setNote(Integer note) {
		this.note = note;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

}
