package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bilan generated by hbm2java
 */
public class Bilan implements java.io.Serializable {

	private int idbilan;
	private Vente vente;
	private Date datedebut;
	private Date datefin;
	private String type;
	private Byte chiffreaffaire;
	private Byte beneficebrut;
	private Byte charge;
	private Byte benefivenet;
	private Set transactions = new HashSet(0);

	public Bilan() {
	}

	public Bilan(int idbilan) {
		this.idbilan = idbilan;
	}

	public Bilan(int idbilan, Vente vente, Date datedebut, Date datefin, String type, Byte chiffreaffaire,
			Byte beneficebrut, Byte charge, Byte benefivenet, Set transactions) {
		this.idbilan = idbilan;
		this.vente = vente;
		this.datedebut = datedebut;
		this.datefin = datefin;
		this.type = type;
		this.chiffreaffaire = chiffreaffaire;
		this.beneficebrut = beneficebrut;
		this.charge = charge;
		this.benefivenet = benefivenet;
		this.transactions = transactions;
	}

	public int getIdbilan() {
		return this.idbilan;
	}

	public void setIdbilan(int idbilan) {
		this.idbilan = idbilan;
	}

	public Vente getVente() {
		return this.vente;
	}

	public void setVente(Vente vente) {
		this.vente = vente;
	}

	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Byte getChiffreaffaire() {
		return this.chiffreaffaire;
	}

	public void setChiffreaffaire(Byte chiffreaffaire) {
		this.chiffreaffaire = chiffreaffaire;
	}

	public Byte getBeneficebrut() {
		return this.beneficebrut;
	}

	public void setBeneficebrut(Byte beneficebrut) {
		this.beneficebrut = beneficebrut;
	}

	public Byte getCharge() {
		return this.charge;
	}

	public void setCharge(Byte charge) {
		this.charge = charge;
	}

	public Byte getBenefivenet() {
		return this.benefivenet;
	}

	public void setBenefivenet(Byte benefivenet) {
		this.benefivenet = benefivenet;
	}

	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

}
