package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Boutique generated by hbm2java
 */
public class Boutique implements java.io.Serializable {

	private int idboutique;
	private String nom;
	private String adresse;
	private String telephone;
	private String email;
	private String siteweb;
	private String logo;
	private Boolean actif;
	private Date datecreation;
	private Date fermeture;
	private String deviseutilisee;
	private String fuseauhoraire;
	private Byte surface;
	private String statut;
	private String typeboutique;
	private String coordonneesgps;
	private Byte capital;
	private Set evenements = new HashSet(0);
	private Set promotions = new HashSet(0);
	private Set soldes = new HashSet(0);
	private Set stocks = new HashSet(0);
	private Set caisses = new HashSet(0);
	private Set marchandises = new HashSet(0);
	private Set configurationboutiques = new HashSet(0);
	private Set horaireboutiques = new HashSet(0);
	private Set archiveactiviteboutiques = new HashSet(0);

	public Boutique() {
	}

	public Boutique(int idboutique) {
		this.idboutique = idboutique;
	}

	public Boutique(int idboutique, String nom, String adresse, String telephone, String email, String siteweb,
			String logo, Boolean actif, Date datecreation, Date fermeture, String deviseutilisee, String fuseauhoraire,
			Byte surface, String statut, String typeboutique, String coordonneesgps, Byte capital, Set evenements,
			Set promotions, Set soldes, Set stocks, Set caisses, Set marchandises, Set configurationboutiques,
			Set horaireboutiques, Set archiveactiviteboutiques) {
		this.idboutique = idboutique;
		this.nom = nom;
		this.adresse = adresse;
		this.telephone = telephone;
		this.email = email;
		this.siteweb = siteweb;
		this.logo = logo;
		this.actif = actif;
		this.datecreation = datecreation;
		this.fermeture = fermeture;
		this.deviseutilisee = deviseutilisee;
		this.fuseauhoraire = fuseauhoraire;
		this.surface = surface;
		this.statut = statut;
		this.typeboutique = typeboutique;
		this.coordonneesgps = coordonneesgps;
		this.capital = capital;
		this.evenements = evenements;
		this.promotions = promotions;
		this.soldes = soldes;
		this.stocks = stocks;
		this.caisses = caisses;
		this.marchandises = marchandises;
		this.configurationboutiques = configurationboutiques;
		this.horaireboutiques = horaireboutiques;
		this.archiveactiviteboutiques = archiveactiviteboutiques;
	}

	public int getIdboutique() {
		return this.idboutique;
	}

	public void setIdboutique(int idboutique) {
		this.idboutique = idboutique;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSiteweb() {
		return this.siteweb;
	}

	public void setSiteweb(String siteweb) {
		this.siteweb = siteweb;
	}

	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public Boolean getActif() {
		return this.actif;
	}

	public void setActif(Boolean actif) {
		this.actif = actif;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Date getFermeture() {
		return this.fermeture;
	}

	public void setFermeture(Date fermeture) {
		this.fermeture = fermeture;
	}

	public String getDeviseutilisee() {
		return this.deviseutilisee;
	}

	public void setDeviseutilisee(String deviseutilisee) {
		this.deviseutilisee = deviseutilisee;
	}

	public String getFuseauhoraire() {
		return this.fuseauhoraire;
	}

	public void setFuseauhoraire(String fuseauhoraire) {
		this.fuseauhoraire = fuseauhoraire;
	}

	public Byte getSurface() {
		return this.surface;
	}

	public void setSurface(Byte surface) {
		this.surface = surface;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public String getTypeboutique() {
		return this.typeboutique;
	}

	public void setTypeboutique(String typeboutique) {
		this.typeboutique = typeboutique;
	}

	public String getCoordonneesgps() {
		return this.coordonneesgps;
	}

	public void setCoordonneesgps(String coordonneesgps) {
		this.coordonneesgps = coordonneesgps;
	}

	public Byte getCapital() {
		return this.capital;
	}

	public void setCapital(Byte capital) {
		this.capital = capital;
	}

	public Set getEvenements() {
		return this.evenements;
	}

	public void setEvenements(Set evenements) {
		this.evenements = evenements;
	}

	public Set getPromotions() {
		return this.promotions;
	}

	public void setPromotions(Set promotions) {
		this.promotions = promotions;
	}

	public Set getSoldes() {
		return this.soldes;
	}

	public void setSoldes(Set soldes) {
		this.soldes = soldes;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

	public Set getCaisses() {
		return this.caisses;
	}

	public void setCaisses(Set caisses) {
		this.caisses = caisses;
	}

	public Set getMarchandises() {
		return this.marchandises;
	}

	public void setMarchandises(Set marchandises) {
		this.marchandises = marchandises;
	}

	public Set getConfigurationboutiques() {
		return this.configurationboutiques;
	}

	public void setConfigurationboutiques(Set configurationboutiques) {
		this.configurationboutiques = configurationboutiques;
	}

	public Set getHoraireboutiques() {
		return this.horaireboutiques;
	}

	public void setHoraireboutiques(Set horaireboutiques) {
		this.horaireboutiques = horaireboutiques;
	}

	public Set getArchiveactiviteboutiques() {
		return this.archiveactiviteboutiques;
	}

	public void setArchiveactiviteboutiques(Set archiveactiviteboutiques) {
		this.archiveactiviteboutiques = archiveactiviteboutiques;
	}

}
