package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

/**
 * CaisseId generated by hbm2java
 */
public class CaisseId implements java.io.Serializable {

	private int idcaisse;
	private String numeroserie;

	public CaisseId() {
	}

	public CaisseId(int idcaisse, String numeroserie) {
		this.idcaisse = idcaisse;
		this.numeroserie = numeroserie;
	}

	public int getIdcaisse() {
		return this.idcaisse;
	}

	public void setIdcaisse(int idcaisse) {
		this.idcaisse = idcaisse;
	}

	public String getNumeroserie() {
		return this.numeroserie;
	}

	public void setNumeroserie(String numeroserie) {
		this.numeroserie = numeroserie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CaisseId))
			return false;
		CaisseId castOther = (CaisseId) other;

		return (this.getIdcaisse() == castOther.getIdcaisse()) && ((this.getNumeroserie() == castOther.getNumeroserie())
				|| (this.getNumeroserie() != null && castOther.getNumeroserie() != null
						&& this.getNumeroserie().equals(castOther.getNumeroserie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcaisse();
		result = 37 * result + (getNumeroserie() == null ? 0 : this.getNumeroserie().hashCode());
		return result;
	}

}
