package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Catalogue generated by hbm2java
 */
public class Catalogue implements java.io.Serializable {

	private int idcatalogue;
	private String nom;
	private String code;
	private Date datecreation;
	private String etat;
	private String description;
	private Set produits = new HashSet(0);

	public Catalogue() {
	}

	public Catalogue(int idcatalogue) {
		this.idcatalogue = idcatalogue;
	}

	public Catalogue(int idcatalogue, String nom, String code, Date datecreation, String etat, Integer nombreelements,
			String description, Set produits) {
		this.idcatalogue = idcatalogue;
		this.nom = nom;
		this.code = code;
		this.datecreation = datecreation;
		this.etat = etat;
		this.nombreelements = nombreelements;
		this.description = description;
		this.produits = produits;
	}

	public int getIdcatalogue() {
		return this.idcatalogue;
	}

	public void setIdcatalogue(int idcatalogue) {
		this.idcatalogue = idcatalogue;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Integer getNombreelements() {
		return this.nombreelements;
	}

	public void setNombreelements(Integer nombreelements) {
		this.nombreelements = nombreelements;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getProduits() {
		return this.produits;
	}

	public void setProduits(Set produits) {
		this.produits = produits;
	}

}
