package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categorievariete generated by hbm2java
 */
public class Categorievariete implements java.io.Serializable {

	private int idcatvariete;
	private Piece piece;
	private String designation;
	private String code;
	private String etat;
	private Date datecretaion;
	private Integer nombreelements;
	private Set varietes = new HashSet(0);

	public Categorievariete() {
	}

	public Categorievariete(int idcatvariete) {
		this.idcatvariete = idcatvariete;
	}

	public Categorievariete(int idcatvariete, Piece piece, String designation, String code, String etat,
			Date datecretaion, Integer nombreelements, Set varietes) {
		this.idcatvariete = idcatvariete;
		this.piece = piece;
		this.designation = designation;
		this.code = code;
		this.etat = etat;
		this.datecretaion = datecretaion;
		this.nombreelements = nombreelements;
		this.varietes = varietes;
	}

	public int getIdcatvariete() {
		return this.idcatvariete;
	}

	public void setIdcatvariete(int idcatvariete) {
		this.idcatvariete = idcatvariete;
	}

	public Piece getPiece() {
		return this.piece;
	}

	public void setPiece(Piece piece) {
		this.piece = piece;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Date getDatecretaion() {
		return this.datecretaion;
	}

	public void setDatecretaion(Date datecretaion) {
		this.datecretaion = datecretaion;
	}

	public Integer getNombreelements() {
		return this.nombreelements;
	}

	public void setNombreelements(Integer nombreelements) {
		this.nombreelements = nombreelements;
	}

	public Set getVarietes() {
		return this.varietes;
	}

	public void setVarietes(Set varietes) {
		this.varietes = varietes;
	}

}
