package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private int idclient;
	private Integer pointfidelite;
	private Date dateinscription;
	private String coordonneegps;
	private Set commandes = new HashSet(0);
	private Set preferences = new HashSet(0);
	private Set avises = new HashSet(0);

	public Client() {
	}

	public Client(int idclient) {
		this.idclient = idclient;
	}

	public Client(int idclient, Integer pointfidelite, Date dateinscription, String coordonneegps, Set commandes,
			Set preferences, Set avises) {
		this.idclient = idclient;
		this.pointfidelite = pointfidelite;
		this.dateinscription = dateinscription;
		this.coordonneegps = coordonneegps;
		this.commandes = commandes;
		this.preferences = preferences;
		this.avises = avises;
	}

	public int getIdclient() {
		return this.idclient;
	}

	public void setIdclient(int idclient) {
		this.idclient = idclient;
	}

	public Integer getPointfidelite() {
		return this.pointfidelite;
	}

	public void setPointfidelite(Integer pointfidelite) {
		this.pointfidelite = pointfidelite;
	}

	public Date getDateinscription() {
		return this.dateinscription;
	}

	public void setDateinscription(Date dateinscription) {
		this.dateinscription = dateinscription;
	}

	public String getCoordonneegps() {
		return this.coordonneegps;
	}

	public void setCoordonneegps(String coordonneegps) {
		this.coordonneegps = coordonneegps;
	}

	public Set getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set commandes) {
		this.commandes = commandes;
	}

	public Set getPreferences() {
		return this.preferences;
	}

	public void setPreferences(Set preferences) {
		this.preferences = preferences;
	}

	public Set getAvises() {
		return this.avises;
	}

	public void setAvises(Set avises) {
		this.avises = avises;
	}

}
