package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Collaborateur generated by hbm2java
 */
public class Collaborateur implements java.io.Serializable {

	private CollaborateurId id;
	private Utilisateur utilisateur;
	private Date date;
	private Set ventes = new HashSet(0);
	private Set approvisionnements = new HashSet(0);
	private Set livraisons = new HashSet(0);
	private Set contrats = new HashSet(0);
	private Set typecollaborateurs = new HashSet(0);

	public Collaborateur() {
	}

	public Collaborateur(CollaborateurId id, Utilisateur utilisateur) {
		this.id = id;
		this.utilisateur = utilisateur;
	}

	public Collaborateur(CollaborateurId id, Utilisateur utilisateur, Date date, Set ventes, Set approvisionnements,
			Set livraisons, Set contrats, Set typecollaborateurs) {
		this.id = id;
		this.utilisateur = utilisateur;
		this.date = date;
		this.ventes = ventes;
		this.approvisionnements = approvisionnements;
		this.livraisons = livraisons;
		this.contrats = contrats;
		this.typecollaborateurs = typecollaborateurs;
	}

	public CollaborateurId getId() {
		return this.id;
	}

	public void setId(CollaborateurId id) {
		this.id = id;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set getVentes() {
		return this.ventes;
	}

	public void setVentes(Set ventes) {
		this.ventes = ventes;
	}

	public Set getApprovisionnements() {
		return this.approvisionnements;
	}

	public void setApprovisionnements(Set approvisionnements) {
		this.approvisionnements = approvisionnements;
	}

	public Set getLivraisons() {
		return this.livraisons;
	}

	public void setLivraisons(Set livraisons) {
		this.livraisons = livraisons;
	}

	public Set getContrats() {
		return this.contrats;
	}

	public void setContrats(Set contrats) {
		this.contrats = contrats;
	}

	public Set getTypecollaborateurs() {
		return this.typecollaborateurs;
	}

	public void setTypecollaborateurs(Set typecollaborateurs) {
		this.typecollaborateurs = typecollaborateurs;
	}

}
