package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Commande generated by hbm2java
 */
public class Commande implements java.io.Serializable {

	private int id;
	private Livraison livraison;
	private Client client;
	private Lignecommande lignecommande;
	private String reference;
	private Date datecommande;
	private String statut;
	private Double montant;
	private String modepaiement;
	private Set pieces = new HashSet(0);

	public Commande() {
	}

	public Commande(int id) {
		this.id = id;
	}

	public Commande(int id, Livraison livraison, Client client, Lignecommande lignecommande, String reference,
			Date datecommande, String statut, Double montant, String modepaiement, Set pieces) {
		this.id = id;
		this.livraison = livraison;
		this.client = client;
		this.lignecommande = lignecommande;
		this.reference = reference;
		this.datecommande = datecommande;
		this.statut = statut;
		this.montant = montant;
		this.modepaiement = modepaiement;
		this.pieces = pieces;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Livraison getLivraison() {
		return this.livraison;
	}

	public void setLivraison(Livraison livraison) {
		this.livraison = livraison;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Lignecommande getLignecommande() {
		return this.lignecommande;
	}

	public void setLignecommande(Lignecommande lignecommande) {
		this.lignecommande = lignecommande;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Date getDatecommande() {
		return this.datecommande;
	}

	public void setDatecommande(Date datecommande) {
		this.datecommande = datecommande;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public Double getMontant() {
		return this.montant;
	}

	public void setMontant(Double montant) {
		this.montant = montant;
	}

	public String getModepaiement() {
		return this.modepaiement;
	}

	public void setModepaiement(String modepaiement) {
		this.modepaiement = modepaiement;
	}

	public Set getPieces() {
		return this.pieces;
	}

	public void setPieces(Set pieces) {
		this.pieces = pieces;
	}

}
