package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conge generated by hbm2java
 */
public class Conge implements java.io.Serializable {

	private int idconge;
	private Employe employe;
	private Typeconge typeconge;
	private Date datedeb;
	private Date datefin;
	private Set motifs = new HashSet(0);

	public Conge() {
	}

	public Conge(int idconge) {
		this.idconge = idconge;
	}

	public Conge(int idconge, Employe employe, Typeconge typeconge, Date datedeb, Date datefin, Set motifs) {
		this.idconge = idconge;
		this.employe = employe;
		this.typeconge = typeconge;
		this.datedeb = datedeb;
		this.datefin = datefin;
		this.motifs = motifs;
	}

	public int getIdconge() {
		return this.idconge;
	}

	public void setIdconge(int idconge) {
		this.idconge = idconge;
	}

	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	public Typeconge getTypeconge() {
		return this.typeconge;
	}

	public void setTypeconge(Typeconge typeconge) {
		this.typeconge = typeconge;
	}

	public Date getDatedeb() {
		return this.datedeb;
	}

	public void setDatedeb(Date datedeb) {
		this.datedeb = datedeb;
	}

	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}

	public Set getMotifs() {
		return this.motifs;
	}

	public void setMotifs(Set motifs) {
		this.motifs = motifs;
	}

}
