package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fluctuationprix generated by hbm2java
 */
public class Fluctuationprix implements java.io.Serializable {

	private int idhistorique;
	private Byte ancienprix;
	private Byte nouveauprix;
	private Date datechangement;
	private String raison;
	private Set periodes = new HashSet(0);
	private Set pieces = new HashSet(0);

	public Fluctuationprix() {
	}

	public Fluctuationprix(int idhistorique) {
		this.idhistorique = idhistorique;
	}

	public Fluctuationprix(int idhistorique, Byte ancienprix, Byte nouveauprix, Date datechangement, String raison,
			Set periodes, Set pieces) {
		this.idhistorique = idhistorique;
		this.ancienprix = ancienprix;
		this.nouveauprix = nouveauprix;
		this.datechangement = datechangement;
		this.raison = raison;
		this.periodes = periodes;
		this.pieces = pieces;
	}

	public int getIdhistorique() {
		return this.idhistorique;
	}

	public void setIdhistorique(int idhistorique) {
		this.idhistorique = idhistorique;
	}

	public Byte getAncienprix() {
		return this.ancienprix;
	}

	public void setAncienprix(Byte ancienprix) {
		this.ancienprix = ancienprix;
	}

	public Byte getNouveauprix() {
		return this.nouveauprix;
	}

	public void setNouveauprix(Byte nouveauprix) {
		this.nouveauprix = nouveauprix;
	}

	public Date getDatechangement() {
		return this.datechangement;
	}

	public void setDatechangement(Date datechangement) {
		this.datechangement = datechangement;
	}

	public String getRaison() {
		return this.raison;
	}

	public void setRaison(String raison) {
		this.raison = raison;
	}

	public Set getPeriodes() {
		return this.periodes;
	}

	public void setPeriodes(Set periodes) {
		this.periodes = periodes;
	}

	public Set getPieces() {
		return this.pieces;
	}

	public void setPieces(Set pieces) {
		this.pieces = pieces;
	}

}
