package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

/**
 * Gestionnaireboutiques generated by hbm2java
 */
public class Gestionnaireboutiques implements java.io.Serializable {

	private int idgestionnaire;

	public Gestionnaireboutiques() {
	}

	public Gestionnaireboutiques(int idgestionnaire) {
		this.idgestionnaire = idgestionnaire;
	}

	public int getIdgestionnaire() {
		return this.idgestionnaire;
	}

	public void setIdgestionnaire(int idgestionnaire) {
		this.idgestionnaire = idgestionnaire;
	}

}
