package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Time;
import java.util.HashSet;
import java.util.Set;

/**
 * Horaireboutique generated by hbm2java
 */
public class Horaireboutique implements java.io.Serializable {

	private int idhoraire;
	private String joursemaine;
	private Time heureopen;
	private Time heurefermeture;
	private Boolean ouvert;
	private Boolean casimprevu;
	private Set boutiques = new HashSet(0);

	public Horaireboutique() {
	}

	public Horaireboutique(int idhoraire) {
		this.idhoraire = idhoraire;
	}

	public Horaireboutique(int idhoraire, String joursemaine, Time heureopen, Time heurefermeture, Boolean ouvert,
			Boolean casimprevu, Set boutiques) {
		this.idhoraire = idhoraire;
		this.joursemaine = joursemaine;
		this.heureopen = heureopen;
		this.heurefermeture = heurefermeture;
		this.ouvert = ouvert;
		this.casimprevu = casimprevu;
		this.boutiques = boutiques;
	}

	public int getIdhoraire() {
		return this.idhoraire;
	}

	public void setIdhoraire(int idhoraire) {
		this.idhoraire = idhoraire;
	}

	public String getJoursemaine() {
		return this.joursemaine;
	}

	public void setJoursemaine(String joursemaine) {
		this.joursemaine = joursemaine;
	}

	public Time getHeureopen() {
		return this.heureopen;
	}

	public void setHeureopen(Time heureopen) {
		this.heureopen = heureopen;
	}

	public Time getHeurefermeture() {
		return this.heurefermeture;
	}

	public void setHeurefermeture(Time heurefermeture) {
		this.heurefermeture = heurefermeture;
	}

	public Boolean getOuvert() {
		return this.ouvert;
	}

	public void setOuvert(Boolean ouvert) {
		this.ouvert = ouvert;
	}

	public Boolean getCasimprevu() {
		return this.casimprevu;
	}

	public void setCasimprevu(Boolean casimprevu) {
		this.casimprevu = casimprevu;
	}

	public Set getBoutiques() {
		return this.boutiques;
	}

	public void setBoutiques(Set boutiques) {
		this.boutiques = boutiques;
	}

}
