package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Journalactivite generated by hbm2java
 */
public class Journalactivite implements java.io.Serializable {

	private int idjournal;
	private Timestamp dateaction;
	private String typeaction;
	private String description;
	private Set sessions = new HashSet(0);

	public Journalactivite() {
	}

	public Journalactivite(int idjournal) {
		this.idjournal = idjournal;
	}

	public Journalactivite(int idjournal, Timestamp dateaction, String typeaction, String description, Set sessions) {
		this.idjournal = idjournal;
		this.dateaction = dateaction;
		this.typeaction = typeaction;
		this.description = description;
		this.sessions = sessions;
	}

	public int getIdjournal() {
		return this.idjournal;
	}

	public void setIdjournal(int idjournal) {
		this.idjournal = idjournal;
	}

	public Timestamp getDateaction() {
		return this.dateaction;
	}

	public void setDateaction(Timestamp dateaction) {
		this.dateaction = dateaction;
	}

	public String getTypeaction() {
		return this.typeaction;
	}

	public void setTypeaction(String typeaction) {
		this.typeaction = typeaction;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getSessions() {
		return this.sessions;
	}

	public void setSessions(Set sessions) {
		this.sessions = sessions;
	}

}
