package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Lignecommande generated by hbm2java
 */
public class Lignecommande implements java.io.Serializable {

	private int id;
	private Integer quantite;
	private Byte prixu;
	private Byte montant;
	private Set produits = new HashSet(0);
	private Set commandes = new HashSet(0);

	public Lignecommande() {
	}

	public Lignecommande(int id) {
		this.id = id;
	}

	public Lignecommande(int id, Integer quantite, Byte prixu, Byte montant, Set produits, Set commandes) {
		this.id = id;
		this.quantite = quantite;
		this.prixu = prixu;
		this.montant = montant;
		this.produits = produits;
		this.commandes = commandes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

	public Byte getPrixu() {
		return this.prixu;
	}

	public void setPrixu(Byte prixu) {
		this.prixu = prixu;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

	public Set getProduits() {
		return this.produits;
	}

	public void setProduits(Set produits) {
		this.produits = produits;
	}

	public Set getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set commandes) {
		this.commandes = commandes;
	}

}
