package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ligneapprovisionnement generated by hbm2java
 */
public class Ligneapprovisionnement implements java.io.Serializable {

	private int id;
	private Integer quantite;
	private Byte prixu;
	private Byte montant;
	private Set produits = new HashSet(0);
	private Set approvisionnements = new HashSet(0);

	public Ligneapprovisionnement() {
	}

	public Ligneapprovisionnement(int id) {
		this.id = id;
	}

	public Ligneapprovisionnement(int id, Integer quantite, Byte prixu, Byte montant, Set produits,
			Set approvisionnements) {
		this.id = id;
		this.quantite = quantite;
		this.prixu = prixu;
		this.montant = montant;
		this.produits = produits;
		this.approvisionnements = approvisionnements;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

	public Byte getPrixu() {
		return this.prixu;
	}

	public void setPrixu(Byte prixu) {
		this.prixu = prixu;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

	public Set getProduits() {
		return this.produits;
	}

	public void setProduits(Set produits) {
		this.produits = produits;
	}

	public Set getApprovisionnements() {
		return this.approvisionnements;
	}

	public void setApprovisionnements(Set approvisionnements) {
		this.approvisionnements = approvisionnements;
	}

}
