package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Livraison generated by hbm2java
 */
public class Livraison implements java.io.Serializable {

	private int id;
	private Collaborateur collaborateur;
	private String reference;
	private String statut;
	private Date datelivraison;
	private Set commandes = new HashSet(0);

	public Livraison() {
	}

	public Livraison(int id, Collaborateur collaborateur) {
		this.id = id;
		this.collaborateur = collaborateur;
	}

	public Livraison(int id, Collaborateur collaborateur, String reference, String statut, Date datelivraison,
			Set commandes) {
		this.id = id;
		this.collaborateur = collaborateur;
		this.reference = reference;
		this.statut = statut;
		this.datelivraison = datelivraison;
		this.commandes = commandes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Collaborateur getCollaborateur() {
		return this.collaborateur;
	}

	public void setCollaborateur(Collaborateur collaborateur) {
		this.collaborateur = collaborateur;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public Date getDatelivraison() {
		return this.datelivraison;
	}

	public void setDatelivraison(Date datelivraison) {
		this.datelivraison = datelivraison;
	}

	public Set getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set commandes) {
		this.commandes = commandes;
	}

}
