package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Lot generated by hbm2java
 */
public class Lot implements java.io.Serializable {

	private int idlot;
	private Stock stock;
	private Marchandise marchandise;
	private String reference;
	private String description;
	private Integer qtinitiale;
	private Integer qtactuelle;
	private Set pieces = new HashSet(0);

	public Lot() {
	}

	public Lot(int idlot) {
		this.idlot = idlot;
	}

	public Lot(int idlot, Stock stock, Marchandise marchandise, String reference, String description,
			Integer qtinitiale, Integer qtactuelle, Set pieces) {
		this.idlot = idlot;
		this.stock = stock;
		this.marchandise = marchandise;
		this.reference = reference;
		this.description = description;
		this.qtinitiale = qtinitiale;
		this.qtactuelle = qtactuelle;
		this.pieces = pieces;
	}

	public int getIdlot() {
		return this.idlot;
	}

	public void setIdlot(int idlot) {
		this.idlot = idlot;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public Marchandise getMarchandise() {
		return this.marchandise;
	}

	public void setMarchandise(Marchandise marchandise) {
		this.marchandise = marchandise;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getQtinitiale() {
		return this.qtinitiale;
	}

	public void setQtinitiale(Integer qtinitiale) {
		this.qtinitiale = qtinitiale;
	}

	public Integer getQtactuelle() {
		return this.qtactuelle;
	}

	public void setQtactuelle(Integer qtactuelle) {
		this.qtactuelle = qtactuelle;
	}

	public Set getPieces() {
		return this.pieces;
	}

	public void setPieces(Set pieces) {
		this.pieces = pieces;
	}

}
