package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Marchandise generated by hbm2java
 */
public class Marchandise implements java.io.Serializable {

	private int idmarchandise;
	private Boutique boutique;
	private String designation;
	private String reference;
	private String code;
	private String etat;
	private Date datecreation;
	private Set pieces = new HashSet(0);
	private Set produits = new HashSet(0);
	private Set lots = new HashSet(0);

	public Marchandise() {
	}

	public Marchandise(int idmarchandise) {
		this.idmarchandise = idmarchandise;
	}

	public Marchandise(int idmarchandise, Boutique boutique, String designation, String reference, String code,
			String etat, Date datecreation, Set pieces, Set produits, Set lots) {
		this.idmarchandise = idmarchandise;
		this.boutique = boutique;
		this.designation = designation;
		this.reference = reference;
		this.code = code;
		this.etat = etat;
		this.datecreation = datecreation;
		this.pieces = pieces;
		this.produits = produits;
		this.lots = lots;
	}

	public int getIdmarchandise() {
		return this.idmarchandise;
	}

	public void setIdmarchandise(int idmarchandise) {
		this.idmarchandise = idmarchandise;
	}

	public Boutique getBoutique() {
		return this.boutique;
	}

	public void setBoutique(Boutique boutique) {
		this.boutique = boutique;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Set getPieces() {
		return this.pieces;
	}

	public void setPieces(Set pieces) {
		this.pieces = pieces;
	}

	public Set getProduits() {
		return this.produits;
	}

	public void setProduits(Set produits) {
		this.produits = produits;
	}

	public Set getLots() {
		return this.lots;
	}

	public void setLots(Set lots) {
		this.lots = lots;
	}

}
