package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Origine generated by hbm2java
 */
public class Origine implements java.io.Serializable {

	private int idorigine;
	private String nomorigine;
	private Set pieces = new HashSet(0);

	public Origine() {
	}

	public Origine(int idorigine) {
		this.idorigine = idorigine;
	}

	public Origine(int idorigine, String nomorigine, Set pieces) {
		this.idorigine = idorigine;
		this.nomorigine = nomorigine;
		this.pieces = pieces;
	}

	public int getIdorigine() {
		return this.idorigine;
	}

	public void setIdorigine(int idorigine) {
		this.idorigine = idorigine;
	}

	public String getNomorigine() {
		return this.nomorigine;
	}

	public void setNomorigine(String nomorigine) {
		this.nomorigine = nomorigine;
	}

	public Set getPieces() {
		return this.pieces;
	}

	public void setPieces(Set pieces) {
		this.pieces = pieces;
	}

}
