package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Permission generated by hbm2java
 */
public class Permission implements java.io.Serializable {

	private int idpermission;
	private String libelle;
	private Date datecreation;
	private String etat;
	private Set roles = new HashSet(0);

	public Permission() {
	}

	public Permission(int idpermission) {
		this.idpermission = idpermission;
	}

	public Permission(int idpermission, String libelle, Date datecreation, String etat, Set roles) {
		this.idpermission = idpermission;
		this.libelle = libelle;
		this.datecreation = datecreation;
		this.etat = etat;
		this.roles = roles;
	}

	public int getIdpermission() {
		return this.idpermission;
	}

	public void setIdpermission(int idpermission) {
		this.idpermission = idpermission;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

}
