package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Piece generated by hbm2java
 */
public class Piece implements java.io.Serializable {

	private int idpiece;
	private Approvisionnement approvisionnement;
	private Lot lot;
	private Origine origine;
	private Marchandise marchandise;
	private Date datecreation;
	private String etat;
	private String reference;
	private String qrcode;
	private Byte prixachat;
	private Byte prixvente;
	private Boolean promotion;
	private String paysorigine;
	private String description;
	private Set categorievarietes = new HashSet(0);
	private Set fluctuationprixes = new HashSet(0);
	private Set commandes = new HashSet(0);

	public Piece() {
	}

	public Piece(int idpiece) {
		this.idpiece = idpiece;
	}

	public Piece(int idpiece, Approvisionnement approvisionnement, Lot lot, Origine origine, Marchandise marchandise,
			Date datecreation, String etat, String reference, String qrcode, Byte prixachat, Byte prixvente,
			Boolean promotion, String paysorigine, String description, Set categorievarietes, Set fluctuationprixes,
			Set commandes) {
		this.idpiece = idpiece;
		this.approvisionnement = approvisionnement;
		this.lot = lot;
		this.origine = origine;
		this.marchandise = marchandise;
		this.datecreation = datecreation;
		this.etat = etat;
		this.reference = reference;
		this.qrcode = qrcode;
		this.prixachat = prixachat;
		this.prixvente = prixvente;
		this.promotion = promotion;
		this.paysorigine = paysorigine;
		this.description = description;
		this.categorievarietes = categorievarietes;
		this.fluctuationprixes = fluctuationprixes;
		this.commandes = commandes;
	}

	public int getIdpiece() {
		return this.idpiece;
	}

	public void setIdpiece(int idpiece) {
		this.idpiece = idpiece;
	}

	public Approvisionnement getApprovisionnement() {
		return this.approvisionnement;
	}

	public void setApprovisionnement(Approvisionnement approvisionnement) {
		this.approvisionnement = approvisionnement;
	}

	public Lot getLot() {
		return this.lot;
	}

	public void setLot(Lot lot) {
		this.lot = lot;
	}

	public Origine getOrigine() {
		return this.origine;
	}

	public void setOrigine(Origine origine) {
		this.origine = origine;
	}

	public Marchandise getMarchandise() {
		return this.marchandise;
	}

	public void setMarchandise(Marchandise marchandise) {
		this.marchandise = marchandise;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	public Byte getPrixachat() {
		return this.prixachat;
	}

	public void setPrixachat(Byte prixachat) {
		this.prixachat = prixachat;
	}

	public Byte getPrixvente() {
		return this.prixvente;
	}

	public void setPrixvente(Byte prixvente) {
		this.prixvente = prixvente;
	}

	public Boolean getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Boolean promotion) {
		this.promotion = promotion;
	}

	public String getPaysorigine() {
		return this.paysorigine;
	}

	public void setPaysorigine(String paysorigine) {
		this.paysorigine = paysorigine;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getCategorievarietes() {
		return this.categorievarietes;
	}

	public void setCategorievarietes(Set categorievarietes) {
		this.categorievarietes = categorievarietes;
	}

	public Set getFluctuationprixes() {
		return this.fluctuationprixes;
	}

	public void setFluctuationprixes(Set fluctuationprixes) {
		this.fluctuationprixes = fluctuationprixes;
	}

	public Set getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set commandes) {
		this.commandes = commandes;
	}

}
