package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit implements java.io.Serializable {

	private int idproduit;
	private Ligneapprovisionnement ligneapprovisionnement;
	private Stock stock;
	private Marchandise marchandise;
	private Famille famille;
	private Lignecommande lignecommande;
	private Lignevente lignevente;
	private String designation;
	private String reference;
	private String code;
	private String etat;
	private Date datecreation;
	private Byte prix;
	private String qrcode;
	private String nom;
	private String description;
	private Set catalogues = new HashSet(0);

	public Produit() {
	}

	public Produit(int idproduit) {
		this.idproduit = idproduit;
	}

	public Produit(int idproduit, Ligneapprovisionnement ligneapprovisionnement, Stock stock, Marchandise marchandise,
			Famille famille, Lignecommande lignecommande, Lignevente lignevente, String designation, String reference,
			String code, String etat, Date datecreation, Byte prix, String qrcode, String nom, String description,
			Set catalogues) {
		this.idproduit = idproduit;
		this.ligneapprovisionnement = ligneapprovisionnement;
		this.stock = stock;
		this.marchandise = marchandise;
		this.famille = famille;
		this.lignecommande = lignecommande;
		this.lignevente = lignevente;
		this.designation = designation;
		this.reference = reference;
		this.code = code;
		this.etat = etat;
		this.datecreation = datecreation;
		this.prix = prix;
		this.qrcode = qrcode;
		this.nom = nom;
		this.description = description;
		this.catalogues = catalogues;
	}

	public int getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(int idproduit) {
		this.idproduit = idproduit;
	}

	public Ligneapprovisionnement getLigneapprovisionnement() {
		return this.ligneapprovisionnement;
	}

	public void setLigneapprovisionnement(Ligneapprovisionnement ligneapprovisionnement) {
		this.ligneapprovisionnement = ligneapprovisionnement;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public Marchandise getMarchandise() {
		return this.marchandise;
	}

	public void setMarchandise(Marchandise marchandise) {
		this.marchandise = marchandise;
	}

	public Famille getFamille() {
		return this.famille;
	}

	public void setFamille(Famille famille) {
		this.famille = famille;
	}

	public Lignecommande getLignecommande() {
		return this.lignecommande;
	}

	public void setLignecommande(Lignecommande lignecommande) {
		this.lignecommande = lignecommande;
	}

	public Lignevente getLignevente() {
		return this.lignevente;
	}

	public void setLignevente(Lignevente lignevente) {
		this.lignevente = lignevente;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Byte getPrix() {
		return this.prix;
	}

	public void setPrix(Byte prix) {
		this.prix = prix;
	}

	public String getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getCatalogues() {
		return this.catalogues;
	}

	public void setCatalogues(Set catalogues) {
		this.catalogues = catalogues;
	}

}
