package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Promotion generated by hbm2java
 */
public class Promotion implements java.io.Serializable {

	private int idpromotion;
	private Boutique boutique;
	private Periode periode;
	private String description;
	private Date date;

	public Promotion() {
	}

	public Promotion(int idpromotion) {
		this.idpromotion = idpromotion;
	}

	public Promotion(int idpromotion, Boutique boutique, Periode periode, String description, Date date) {
		this.idpromotion = idpromotion;
		this.boutique = boutique;
		this.periode = periode;
		this.description = description;
		this.date = date;
	}

	public int getIdpromotion() {
		return this.idpromotion;
	}

	public void setIdpromotion(int idpromotion) {
		this.idpromotion = idpromotion;
	}

	public Boutique getBoutique() {
		return this.boutique;
	}

	public void setBoutique(Boutique boutique) {
		this.boutique = boutique;
	}

	public Periode getPeriode() {
		return this.periode;
	}

	public void setPeriode(Periode periode) {
		this.periode = periode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
