package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.sql.Time;

/**
 * Sessioncaisse generated by hbm2java
 */
public class Sessioncaisse implements java.io.Serializable {

	private int idsession;
	private Caisse caisse;
	private Date date;
	private Time heure;
	private Byte montant;
	private String type;

	public Sessioncaisse() {
	}

	public Sessioncaisse(int idsession) {
		this.idsession = idsession;
	}

	public Sessioncaisse(int idsession, Caisse caisse, Date date, Time heure, Byte montant, String type) {
		this.idsession = idsession;
		this.caisse = caisse;
		this.date = date;
		this.heure = heure;
		this.montant = montant;
		this.type = type;
	}

	public int getIdsession() {
		return this.idsession;
	}

	public void setIdsession(int idsession) {
		this.idsession = idsession;
	}

	public Caisse getCaisse() {
		return this.caisse;
	}

	public void setCaisse(Caisse caisse) {
		this.caisse = caisse;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Time getHeure() {
		return this.heure;
	}

	public void setHeure(Time heure) {
		this.heure = heure;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
