package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

/**
 * Solde generated by hbm2java
 */
public class Solde implements java.io.Serializable {

	private int idsolde;
	private Boutique boutique;
	private Byte montant;

	public Solde() {
	}

	public Solde(int idsolde) {
		this.idsolde = idsolde;
	}

	public Solde(int idsolde, Boutique boutique, Byte montant) {
		this.idsolde = idsolde;
		this.boutique = boutique;
		this.montant = montant;
	}

	public int getIdsolde() {
		return this.idsolde;
	}

	public void setIdsolde(int idsolde) {
		this.idsolde = idsolde;
	}

	public Boutique getBoutique() {
		return this.boutique;
	}

	public void setBoutique(Boutique boutique) {
		this.boutique = boutique;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

}
