package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private int idstock;
	private Boutique boutique;
	private Employe employe;
	private String designation;
	private String reference;
	private Integer quantiteenstock;
	private Date datecreation;
	private String etat;
	private Integer quantiterestance;
	private Byte depenses;
	private Byte ventecumul;
	private Byte benefices;
	private Set lots = new HashSet(0);
	private Set produits = new HashSet(0);

	public Stock() {
	}

	public Stock(int idstock) {
		this.idstock = idstock;
	}

	public Stock(int idstock, Boutique boutique, Employe employe, String designation, String reference,
			Integer quantiteenstock, Date datecreation, String etat, Integer quantiterestance, Byte depenses,
			Byte ventecumul, Byte benefices, Set lots, Set produits) {
		this.idstock = idstock;
		this.boutique = boutique;
		this.employe = employe;
		this.designation = designation;
		this.reference = reference;
		this.quantiteenstock = quantiteenstock;
		this.datecreation = datecreation;
		this.etat = etat;
		this.quantiterestance = quantiterestance;
		this.depenses = depenses;
		this.ventecumul = ventecumul;
		this.benefices = benefices;
		this.lots = lots;
		this.produits = produits;
	}

	public int getIdstock() {
		return this.idstock;
	}

	public void setIdstock(int idstock) {
		this.idstock = idstock;
	}

	public Boutique getBoutique() {
		return this.boutique;
	}

	public void setBoutique(Boutique boutique) {
		this.boutique = boutique;
	}

	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Integer getQuantiteenstock() {
		return this.quantiteenstock;
	}

	public void setQuantiteenstock(Integer quantiteenstock) {
		this.quantiteenstock = quantiteenstock;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Integer getQuantiterestance() {
		return this.quantiterestance;
	}

	public void setQuantiterestance(Integer quantiterestance) {
		this.quantiterestance = quantiterestance;
	}

	public Byte getDepenses() {
		return this.depenses;
	}

	public void setDepenses(Byte depenses) {
		this.depenses = depenses;
	}

	public Byte getVentecumul() {
		return this.ventecumul;
	}

	public void setVentecumul(Byte ventecumul) {
		this.ventecumul = ventecumul;
	}

	public Byte getBenefices() {
		return this.benefices;
	}

	public void setBenefices(Byte benefices) {
		this.benefices = benefices;
	}

	public Set getLots() {
		return this.lots;
	}

	public void setLots(Set lots) {
		this.lots = lots;
	}

	public Set getProduits() {
		return this.produits;
	}

	public void setProduits(Set produits) {
		this.produits = produits;
	}

}
