package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	private int idtransaction;
	private Bilan bilan;
	private Vente vente;
	private Date datetransaction;
	private String type;
	private Byte montant;
	private String description;
	private String piececomptable;

	public Transaction() {
	}

	public Transaction(int idtransaction) {
		this.idtransaction = idtransaction;
	}

	public Transaction(int idtransaction, Bilan bilan, Vente vente, Date datetransaction, String type, Byte montant,
			String description, String piececomptable) {
		this.idtransaction = idtransaction;
		this.bilan = bilan;
		this.vente = vente;
		this.datetransaction = datetransaction;
		this.type = type;
		this.montant = montant;
		this.description = description;
		this.piececomptable = piececomptable;
	}

	public int getIdtransaction() {
		return this.idtransaction;
	}

	public void setIdtransaction(int idtransaction) {
		this.idtransaction = idtransaction;
	}

	public Bilan getBilan() {
		return this.bilan;
	}

	public void setBilan(Bilan bilan) {
		this.bilan = bilan;
	}

	public Vente getVente() {
		return this.vente;
	}

	public void setVente(Vente vente) {
		this.vente = vente;
	}

	public Date getDatetransaction() {
		return this.datetransaction;
	}

	public void setDatetransaction(Date datetransaction) {
		this.datetransaction = datetransaction;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPiececomptable() {
		return this.piececomptable;
	}

	public void setPiececomptable(String piececomptable) {
		this.piececomptable = piececomptable;
	}

}
