package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Typeconge generated by hbm2java
 */
public class Typeconge implements java.io.Serializable {

	private int idtypeconge;
	private String libelle;
	private String description;
	private Set conges = new HashSet(0);

	public Typeconge() {
	}

	public Typeconge(int idtypeconge) {
		this.idtypeconge = idtypeconge;
	}

	public Typeconge(int idtypeconge, String libelle, String description, Set conges) {
		this.idtypeconge = idtypeconge;
		this.libelle = libelle;
		this.description = description;
		this.conges = conges;
	}

	public int getIdtypeconge() {
		return this.idtypeconge;
	}

	public void setIdtypeconge(int idtypeconge) {
		this.idtypeconge = idtypeconge;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getConges() {
		return this.conges;
	}

	public void setConges(Set conges) {
		this.conges = conges;
	}

}
