package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Variete generated by hbm2java
 */
public class Variete implements java.io.Serializable {

	private VarieteId id;
	private Categorievariete categorievariete;
	private String designation;
	private String code;
	private String etat;
	private Date datecreation;

	public Variete() {
	}

	public Variete(VarieteId id, Categorievariete categorievariete) {
		this.id = id;
		this.categorievariete = categorievariete;
	}

	public Variete(VarieteId id, Categorievariete categorievariete, String designation, String code, String etat,
			Date datecreation) {
		this.id = id;
		this.categorievariete = categorievariete;
		this.designation = designation;
		this.code = code;
		this.etat = etat;
		this.datecreation = datecreation;
	}

	public VarieteId getId() {
		return this.id;
	}

	public void setId(VarieteId id) {
		this.id = id;
	}

	public Categorievariete getCategorievariete() {
		return this.categorievariete;
	}

	public void setCategorievariete(Categorievariete categorievariete) {
		this.categorievariete = categorievariete;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

}
