package com.gescom.model;
// Generated 1 avr. 2025, 20:05:00 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Vente generated by hbm2java
 */
public class Vente implements java.io.Serializable {

	private int idvente;
	private Employe employe;
	private Lignevente lignevente;
	private Byte montant;
	private String reference;
	private Set collaborateurs = new HashSet(0);
	private Set bilans = new HashSet(0);
	private Set transactions = new HashSet(0);

	public Vente() {
	}

	public Vente(int idvente) {
		this.idvente = idvente;
	}

	public Vente(int idvente, Employe employe, Lignevente lignevente, Byte montant, String reference,
			Set collaborateurs, Set bilans, Set transactions) {
		this.idvente = idvente;
		this.employe = employe;
		this.lignevente = lignevente;
		this.montant = montant;
		this.reference = reference;
		this.collaborateurs = collaborateurs;
		this.bilans = bilans;
		this.transactions = transactions;
	}

	public int getIdvente() {
		return this.idvente;
	}

	public void setIdvente(int idvente) {
		this.idvente = idvente;
	}

	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	public Lignevente getLignevente() {
		return this.lignevente;
	}

	public void setLignevente(Lignevente lignevente) {
		this.lignevente = lignevente;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Set getCollaborateurs() {
		return this.collaborateurs;
	}

	public void setCollaborateurs(Set collaborateurs) {
		this.collaborateurs = collaborateurs;
	}

	public Set getBilans() {
		return this.bilans;
	}

	public void setBilans(Set bilans) {
		this.bilans = bilans;
	}

	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

}
